"""empty message

Revision ID: 1e1d590aa588
Revises: a6749f361981
Create Date: 2016-01-20 11:51:25.240299

"""

# revision identifiers, used by Alembic.
revision = '1e1d590aa588'
down_revision = 'a6749f361981'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standing', sa.Column('sid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standing', 'sid')
    ### end Alembic commands ###
