"""empty message

Revision ID: a6749f361981
Revises: fe98292c763e
Create Date: 2016-01-20 10:05:16.678588

"""

# revision identifiers, used by Alembic.
revision = 'a6749f361981'
down_revision = 'fe98292c763e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standing', sa.Column('score2', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standing', 'score2')
    ### end Alembic commands ###
