"""empty message

Revision ID: dfa692d7f778
Revises: e802fcf7cd2e
Create Date: 2016-01-20 00:53:09.713985

"""

# revision identifiers, used by Alembic.
revision = 'dfa692d7f778'
down_revision = 'e802fcf7cd2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('score', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'score')
    ### end Alembic commands ###
