"""empty message

Revision ID: fe98292c763e
Revises: dfa692d7f778
Create Date: 2016-01-20 09:39:43.257823

"""

# revision identifiers, used by Alembic.
revision = 'fe98292c763e'
down_revision = 'dfa692d7f778'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standing', sa.Column('score', sa.Integer(), nullable=True))
    op.drop_column('standing', 'penalty')
    op.drop_column('standing', 'actime')
    op.drop_column('standing', 'submissions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standing', sa.Column('submissions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('standing', sa.Column('actime', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('standing', sa.Column('penalty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('standing', 'score')
    ### end Alembic commands ###
